- name: Install system packages
  pacman: 
    name: ['curl', 'wget','tar','unzip','zip','base-devel','stow','openssh','alacritty','xclip','xdotool', 'tmux']
  tags:
    - system

- name: Install Language Supports
  pacman:
    name: ['go', 'rust', 'luarocks','dotnet-sdk']
  tags:
    - languages



- name: Install debugpy
  pacman: 
    name: ['python-debugpy', 'python-virtualenv', 'python-pip']

  tags:
    - python

- name: Install Node
  pacman:
    name: ['nodejs', 'npm', 'pnpm']
  tags:
    - node
    
- name: Clone yay repository
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay.git
    dest: ~/Downloads/yay
  tags:
    - yay
  become: false

- name: Build and install
  ansible.builtin.shell:
    cmd: "makepkg -si --noconfirm"
    chdir: "~/Downloads/yay"
  tags:
    - yay
  become: false


- name: Remove yay directory
  ansible.builtin.shell:
    cmd: "rm -rf yay"
    chdir: "~/Downloads/"
  tags:
    - yay
  become: false




- name: Install konsave
  ansible.builtin.command:
    cmd: yay -S --noconfirm konsave
  tags:
    - konsave
  become: false


